# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendFileStatusModel',
            fields=[
                ('filename', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('enabled_date', models.DateTimeField()),
                ('in_use', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField()),
            ],
        ),
    ]
