# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendFileStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('in_use', models.BooleanField()),
            ],
        ),
    ]
