# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170721_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendfilestatusmodel',
            name='enabled_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='frontendfilestatusmodel',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
