# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170720_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendfilestatusmodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
